name: "npm"

on:
  workflow_call:
    inputs:
      nodeVersion:
        description: "Node.js version"
        type: number
        required: true

jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - name: apt-get install curl
      run: |
        sudo apt-get update \
          && sudo apt-get install ca-certificates curl gnupg --yes
      shell: bash
    - name: download nodesource .gpg key
      run: |
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
          | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
      shell: bash
    - name: create deb repository
      run: |
        echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${{ inputs.nodeVersion }}.x nodistro main" \
          | sudo tee /etc/apt/sources.list.d/nodesource.list
      shell: bash
    - name: apt-get install nodejs
      run: |
        sudo apt-get update \
          && sudo apt-get install nodejs --yes
      shell: bash
